- .gitignore
The repo currently includes `factorio-server-manager` and `factorio-server-manger.exe`. This PR removes them from the repo.
If you're up for rewriting history, consider `git reset`ing (and force-pushing) master to match my `exclude_binaries_rewrite_history` branch, currently 68f99575147a5757208235b9fa3f84339dae0e95. This is the result of [`bfg`](https://rtyley.github.io/bfg-repo-cleaner/)` --delete-files '{factorio-server-manager,factorio-server-manger.exe}'`, and it removes the binaries from the repo's history, shrinking everyone's future repo clones by 16 MB.
> Exclude binaries

- docker/Dockerfile
- docker/init.sh
- docker/nginx.conf
Fixed: 404 on refresh of suppages ( #18 )
Fixed: errors during download/upload of big files ( #14 )
Dockerfile:22-26 might be confusing, but this is the only way to avoid a docker bug I encountered.
> Docker: reverse proxy bugfixes 

- src/mods.go
Ignore file already exist errors. The "modpacks" directory will exist at least on the second launch.
> Fix error check conditional

- docker/Dockerfile
The container fails to build because 0.12.33 returns an internal server error. Use the latest server build by default.
> Default to the latest factorio server

- src/main.go
On windows the _factorio-current.log_ file is located in _%appdata%/Factorio_. Note, the _mods_ and _saves_ directories are here too.
> Fix file path to factorio-current.log on windows.

- src/routes.go
- ui/App/components/LoginContent.jsx
Right, so it turns out having nginx serve /login as a static file and then post to the same location is rather complex. At least, I couldn't find a clear way to route a GET to a static location and then a POST to the proxy.
So, I figured an easier solution would be to move the login POST to the api router (/api/login).
> Move login to the api router.

- src/server.go
There doesn't seem to be an easy solution to terminating Factorio gracefully on Windows. Until then, kill the process. The map will not be saved so it's not the best solution...
> Stop Factorio on Windows

- src/saves.go
If there were no saves, listSaves would return a nil slice.
> Fix nil pointer in saves

- src/factorio_server.go
- src/handlers.go
- src/main.go
- ui/App/components/ConfigContent.jsx
To prevent future Factorio updates breaking the server settings,
use a map to store settings. Also, comments are now preserved and
used as help text in the UI. Note: they are also passed through
the settings form, but hidden. Also improved: error handling/logging in
FactorioServer init and more error checking in the handler.
> Make FactorioServer.Settings use a map instead of a struct

- docker/Dockerfile
- docker/init.sh
The path of the executable changed from `/opt/factorio-server/factorio-server-manager` to `/opt/factorio-server-manager/factorio-server-manager`. 
Additionally the backend was not able to find the web files without changing to the directory first.
This PR fixes those issues.
> Fix executable path and working directory in Docker Container

- docker/Dockerfile
It seems, that the Factorio download page (https://www.factorio.com/get-download/latest/headless/linux64) now provides a `.tar.xz` file for download instead of a `.gz`.
Changed the Dockerfile accordingly, now it builds again.
> Fix Dockerfile to handle tar.xz downloads

- ui/App/components/Saves/Save.jsx
E.g. on the 25th of May 2017, at 2:13 pm the last modified time showed as "2017-04-25 2:13:00" 
Wrong month (off by one, due to JavaScript Month weirdness) and no am/pm marker (for simplicity switched to military time).
> Fixed save file date not displaying properly

- src/factorio_server.go
see https://wiki.factorio.com/Console#Command_Line_Parameters for details,
forum posts mentioned that this changed happened back in ~1.3.
The wiki itself had these arguments added on jan 20th, 2017, so this is not a new thing.
> change --rcon-pass argument to --rcon-password

- docker/Dockerfile
This keeps people from hitting the `rcon-pass` flag renaming bug in the future.
> Update: use latest manager version in Dockerfile

- src/mod_modInfo.go
Fixed bug, that caused the manager to crash, when no basemodversion is defined.
#118 #113
> fixed crash, when mods have no basemodversion defined

- README.md
- src/factorio_server.go
- src/main.go
Not the most elegant solution, but does the trick for people using RHEL/Centos
I added 3 new parameters and edited the readme file, in short:
-glibc-custom (if you are using custom glibc, true/false, default false)
-glibc-loc (path to the glibc ld.so file)
-glibc-lib-loc (path to the glibc lib folder)
> Fix for the glibc issue on RHEL/Centos

- src/handlers.go
- src/mods_handler.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- .travis.yml
- docker/Dockerfile
- docker/Dockerfile-build
- docker/Makefile
- docker/build.sh
- ui/package-lock.json
Added a dockerfile to create the release packages and added a CI job to automatically upload releases if you tag the version.
> Add dockerfile to build releases

- src/factorio_server.go
- src/wsclient.go
- src/wsroutes.go
I fixed the console #76.
- The Rcon session did not start, because factorio changed a log line. 
- I noticed FSM crashes after the ingame chat was used #165 => `panic: send on closed channel`
If you have trouble to load the UI and it is really slow, just delete the factorio-server-console.log 😉
> Fix console

- src/api/handlers.go
- src/bootstrap/config.go
- src/factorio/server.go
- src/main.go
Hey all!
Love this project, I've only used it for a short time but already can't imagine not having it.  This PR is centered around some non-intuitive install configurations I've run in to using the AUR package for factorio on Arch Linux.  In short, the baseMod lives in `/usr/share`, the executable in `/usr/bin`, and the server settings in `/etc/factorio`, with most everything else falling into `/var/lib/factorio/.factorio`.  I've been able to get it working by symlinking everything to a single directory, but that felt messy and hacky so I modified the config logic to handle absolute paths and allow explicit base mod directory to be specified.  I have not, however, extended this behavior to other settings/paths- so I'm not sure this is the best way forward.
Ultimately, I'd just be happy …
> Handle absolute paths in settings/binary, configurable BaseMod dir

- src/factorio/mod_portal.go
Revert the workaround for the Mod Portal API issue as it's now fixed on their end
> Revert workaround for Mod Portal issue

- docker/Dockerfile-build
- docker/README.md
- docker/build-release.sh
Add packages for Windows compilation, add note to run from root directory to make build files.
> Fix Dockerfile-build for Windows cross compilation

- Makefile
I removed the static linking in the makefile. The build created with `make build` works on my Ubuntu 20.10 VM and on my Ubuntu 18.04 setup.
For some reason the executable created with GoLand is still not usable on 20.10, but that is problem :)
Please also run the script and test the executables on different systems. The docker image built works on my Ubuntu 18.04 system. It can be loaded as `ofsm/ofsm:fix-glibc`.
> dont build static on linux

- docker/Dockerfile
- docker/Dockerfile-local
- src/factorio/saves.go
This fixes problems running factorio, when the server-manager is dynamically linked to glibc.
> use ubuntu base image instead of alpine

- src/bootstrap/config.go
With this change, if conf.json contains all required fields (e.g. doesn't need writing to to set the rcon password etc) then factorio-server-manager will launch even if conf.json is read-only.
Without this change, it fails to start, with:
```
panic: Error loading config file.: open /opt/factorio-server-manager/conf.json: permission denied
```
> Open conf.json in RDONLY when we only need to read it

- src/api/handlers.go
- src/bootstrap/config.go
- src/factorio/server.go
This patch makes it possible to configure where the `server-adminlist.json` is located, which is useful if it's not in your Factorio configuration dir.
I also made it possible to specify a non-relative path to it, similar to some of the other options . This is helpful for me because all my writeable data is in an entirely separate location.
> Make admin file location configurable

- src/bootstrap/config.go
- src/factorio/server.go
This patch makes it possible to configure where the `factorio-server-console.log` file is located. Without this, I was getting a lot of write errors in the logs, because my Factorio directory is not writeable.
> Make server console log file path configurable

- src/bootstrap/config.go
Rcon port taken from config file or generated random if not set
Mentioned in issue [240](https://github.com/OpenFactorioServerManager/factorio-server-manager/issues/240)
> Rcon port config
