- docker/Dockerfile
- docker/README.md
- docker/init.sh
- docker/nginx.conf
For my personal needs I've created a docker image with a nginx reverse proxy and SSL prepared. It also contains some basic authentication. 
This image is not yet pushed to dockerhub, I guess you being the project owner should do if you want to. 
Oh, and you should check the Readme for spelling mistakes. English is not my first language :P
> Added new Dockerfile with nginx reverse proxy

- docker/Dockerfile
- docker/README.md
docker: 
new factorio version and documentation
> docker: fixed documentation and added 0.13.32

- docker/Makefile
Some cleanup and adding logs, stop, and clean commands
> Docker makefile

- docker/Dockerfile
- docker/nginx.conf
Update to 0.4.0 version
Misc fixes
> Docker version fix

- ui/App/components/Sidebar.jsx
Changed the link icons to something better.
> Changed Icons

- src/server.go
Added full save file path to startup argument.
> Modified server-start command for .13

- docker/Dockerfile
Fix missing openssl dependency.
> Add openssl to Dockerfile

- docker/Dockerfile
- docker/nginx.conf
The container didn't initially run for me; nginx process wasn't running because the logs directory missing. It runs now, including a few edits I made along the way.
> Fix Dockerfile and nginx.conf

- conf.json.example
- src/auth.go
- src/main.go
- src/routes.go
- ui/App/components/LoginContent.jsx
Figured it might be helpful to set the key used to encrypt the cookie files. Compressed _createAuthDb_ and 
_createRoles_ into _CreateAuth_.
> Configure cookie encryption key.

- src/handlers.go
- src/server.go
The new map I created was saved next to the go executable and not in the _Factorio/saves_ directory.
> Fix create save file

- src/handlers.go
- src/saves.go
Altered Save to be more idiomatic. Moved error handling and logging to their respective HTTP handlers.
> Clean up of Save and move error handling to handlers

- docker/docker-compose.yml
While setting up the docker container I was missing an easy-to-edit docker-compose file, so I added it.
> add docker-compose.yml

- .gitignore
- Makefile
- README.md
- gopkglist
No more commented out code, and the finished product actually runs now.
Also updated the readme to reflect the new build rules.
> Cleaned up the build script

- ui/App/components/ConfigContent.jsx
> Fixes Config Tab Boolean Settings

- src/factorio_server.go
- src/handlers.go
- src/mod_modInfo.go
- src/mods.go
- src/version.go
Simplified base dependency checking for mod.json. Fixes #123 and should fix #124.
> fix #123: incorrect incompatibility flags

- src/factorio_save.go
- src/factorio_server.go
- src/mod_modInfo.go
- src/mods.go
- src/mods_handler.go
Some files are not closed, so they couldnt be opened later, to delete them.
Also i added a few tests, that errors will be thrown, when the closing didn't worked (only in a few places).
This fixes #163 and fixes #154
> added missing file closing

- README.md
- src/factorio_server.go
- src/main.go
> Autostart feature

- docker/Dockerfile
- docker/Dockerfile-build
- docker/README.md
- docker/build-release.sh
- docker/docker-compose.simple.yaml
- docker/docker-compose.yaml
Add back the removed docker container to create release bundles.
> Add docker container to build release bundles

- src/bootstrap/config.go
> fixed rcon port not randomized

- CHANGELOG.md
- docker/Dockerfile
- docker/Dockerfile-local
- docker/docker-compose.simple.yaml
- docker/entrypoint.sh
- src/bootstrap/config.go
> Docker fixes

- README.md
Hello,
Thanks for this very useful project to maintain a factorio server easily.
I was looking at automating the restart of the server after a reboot to make the maintenance even easier. Since I'm using the docker compose file, it's already mostly taken care of since the container restarts automatically, but the factorio server doesn't restart by default.
As I was trying to figure out how to automate this part, I spent some time figuring out how to get through the API authentication, so I'm publishing these instructions to help anyone else who would like to build some automation on top of factorio-server-manager
Cheers.
> Add instructions for API auth

- ui/App/views/Controls.jsx
Fix for #202 
The Select for the Save will now autoselect the "Load Latest" Save.
> autoselect "Load Latest" Save in Controls.jsx

- docker/docker-compose.simple.yaml
- docker/docker-compose.yaml
Add a volume map for mod_packs to docker compose dir to facilitate them persisting after an image refresh
> Add a map for mod_packs to docker compose dir

- src/factorio/server.go
- ui/App/views/Controls.jsx
Displays an error message if only "Load Latest" save is returned.
> Display error if server started without save created

- src/api/auth.go
- ui/api/resources/user.js
Prevent deleting single admin user.
> Single admin delete
